# This is a basic workflow to help you get started with Actions

name: Dependencyupdate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains job that runs Lint on all applicable repositories
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2

      # Set up Node and NPM
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.3
          scope: '@gpa-gemstone'

      - name: Lint_CommonPages
        run: |
          cd $GITHUB_WORKSPACE/common-pages/
          npm install
          npm run lint

      - name: Lint_GPASymbols
        run: |
          cd $GITHUB_WORKSPACE/gpa-symbols/
          npm install
          npm run lint

      - name: Lint_HelperFunctions
        run: |
          cd $GITHUB_WORKSPACE/helper-functions/
          npm install
          npm run lint

      - name: Lint_ReactForms
        run: |
          cd $GITHUB_WORKSPACE/react-forms/
          npm install
          npm run lint

      - name: Lint_ReactGraph
        run: |
          cd $GITHUB_WORKSPACE/react-graph/
          npm install
          npm run lint

      - name: Lint_ReactInteractive
        run: |
          cd $GITHUB_WORKSPACE/react-interactive/
          npm install
          npm run lint

      - name: Lint_ReactTable
        run: |
          cd $GITHUB_WORKSPACE/react-table/
          npm install
          npm run lint
